name: validate-models

on:
  pull_request:
    branches: [main, test_validation_action]
    paths:
      - '**/*'
jobs:
  validate-repository-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/iot-plugandplay-models-tools/.github/actions/validate-models@dev
